# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      parallelization:
        description: "Fully Parallel?"
        default: true
        required: false
        type: boolean
      workersNumber:
        description: "Number of Workers"
        required: false
        type: string
      retriesNumber:
        description: "Number of Retries"
        default: "0"
        required: false
        type: string
      testFileRelativePath:
        description: "Specify Test File Relative Path"
        type: string
        required: true
      testDescribeMode:
        description: "Specify Parallelization for the test file(s)"
        type: choice
        required: false
        options:
          - "serial"
          - "parallel"
      prmTokenTry:
        description: "Token"
        type: string
env:
  HOME: "24mx"
jobs:
  ui_automation_tests:
    runs-on: [ubuntu-latest]
    container:
      image: mcr.microsoft.com/playwright:v1.42.1-jammy
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies

        run: |
          ls

          npm install moment
          npm install events
          npx playwright --version
      - name: Install Playwright Browsers
        run: npx playwright install chrome
      - name: Run Playwright tests
        env:
          #spaces after ":" -> "var: secret"
          parallelization: ${{ inputs.parallelization }}
          numberOfWorkers: ${{ inputs.workersNumber }}
          numberOfRetries: ${{ inputs.retriesNumber }}
          testDescribeMode: ${{ inputs.testDescribeMode }}
        run: |
          ls
          cd ${{ env.HOME }}

          npx playwright test ${{inputs.testFileRelativePath}}
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: |
            playwright/playwright-report/
            playwright/playwright-report/**
            playwright/tests/runData.js
          retention-days: 1
